# A simple name for the workflow
name: Assignment Action

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Runs on pushes to the w1 branch (optional, but good practice)
  push:
    branches: [ w1 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v4

      # This is the required step with your email in the name
      - name: A simple step run by 24f1001129@ds.study.iitm.ac.in
        run: echo "This step ran successfully for the assignment!"
