name: My Custom Workflow

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f1001129@ds.study.iitm.ac.in
        run: echo "This step is named with the email address. Hasta la Vista"
